### ISSUE TITLE
Issue creating htpasswd

### ISSUE THREAD

**Issue by danielsamfdo** [rtmatt/Htpasswd#1]
vagrant@homestead:~/em_portal$ sudo php artisan htpasswd:make daniel

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "htpasswd" namespace.

**Comment by rtmatt** [comment]
I haven't looked at this code in a long time and never used it extensively.  I'll have a look in the next few days.

**Comment by rtmatt** [comment]
Unable to reproduce.
